sudo: false
language: php

php:
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_script:
  - git clone --depth=50 --branch=2017.04 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core
  - mv ../ai-zend2 ext/
  - composer require "zendframework/zend-config" "2.3.*"
  - composer require "zendframework/zend-log" "2.3.*"
  - composer require "zendframework/zend-mail" "2.3.*"
  - composer require "zendframework/zend-mvc" "2.3.*"
  - composer install

script: vendor/bin/phing -Ddir=ext/ai-zend2 coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-zend2/.coveralls.yml
