language: php
php:
  - "hhvm"
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - git clone --depth=50 --branch=master git://github.com/nsendetzky/arcavias-core.git ../arcavias-core
  - cd ../arcavias-core
  - mv ../ai-zend2 ext/
  - composer require "zendframework/zend-config" "2.3.*"
  - composer require "zendframework/zend-i18n" "2.3.*"
  - composer require "zendframework/zend-log" "2.3.*"
  - composer require "zendframework/zend-mail" "2.3.*"
  - composer require "zendframework/zend-mvc" "2.3.*"
  - composer install
script: "vendor/bin/phing -Ddir=ext/ai-zend2 testext && vendor/bin/phing -Ddir=ext/ai-zend2 checkext"
